### ISSUE TITLE
Implement a proper color quantization algorithm

### ISSUE THREAD

**Issue by BonQerss** [Pioziomgames/GJConv#1]
I'm using this tool to batch convert tmx files to indexed 8 bit, but most of them end up with incredibly limited colors. Some turn out fine but most are completely incorrect.

The command I pass to it is converting the tmx to png, halving the resolution, then converting the png to tmx like this:

for %%f in (*.png) do for %%g in ("%%~nf") do "C:\Users\drewk\OneDrive\Desktop\Mod Porting\TMX\tools\GJConv\gjconv" "%%f" -id "%%~pf\%%~nf.tmx"

The output files look something like this:
![image](https://user-images.githubusercontent.com/104710767/235972310-9e8634bb-045f-4762-8e77-14dae18bc72c.png)
![image (4)](https://user-images.githubusercontent.com/104710767/235972325-76fbc97d-77dd-45af-a910-988275dcefed.png)
![image (3)](https://user-images.githubusercontent.com/104710767/235972341-60ab368e-4366-4784-b0cb-105399db52f3.png)
![image (2)](https://user-images.githubusercontent.com/104710767/235972370-99e50e4c-0f0e-4a88-91d8-5055ec52ce94.png)
![image (1)](https://user-images.githubusercontent.com/104710767/235972387-f9f582b5-750c-43f6-ad21-30026ebeecd0.png)

Any ideas? Or is 8 bit tmx support not fully fleshed out?

**Comment by BonQerss** [comment]
Think I found the issue. When passing indexed as an argument it sets the palette count to 1, instead of 0 like everything else. At least I think that's the issue.

**Comment by pionome** [comment]
The current color limiting implementation is very bare bones and simply chooses the most used colors and doesn't actually care about what colors those are, a proper color quantization algorithm is planned to be added soon but for now I recommend the of a  different program(such as pngquant or imagemagick) to limit the colors of your images before converting.

**Comment by BonQerss** [comment]
That works for me too! If you pass the argument "-colors 256" when converting imagemagick, all images come out properly.
Thanks for the good explanation and the speedy reply!
![Screenshot 2023-05-04 084816](https://user-images.githubusercontent.com/104710767/236260681-5211f177-8508-4217-b424-7f4ad823a15c.png)

**Comment by pionome** [comment]
Adressed in: 01755df
